### ISSUE TITLE
TypeError: str expected, not int

### ISSUE THREAD

**Issue by Elijas** [ricklamers/shell-ai#1]
<img width="806" alt="image" src="https://github.com/ricklamers/shell-ai/assets/4084885/9e00da6b-4f61-44e2-a121-140ce68c2212">

**Comment by ricklamers** [comment]
I should probably mention that the key and value should both be strings in the `config.json` file.

**Comment by ricklamers** [comment]
https://github.com/ricklamers/shell-ai/commit/9b418050fa1b37e9b9b7d53b65d0b62f2fe6735a

This will circumvent the issue in case people don't make keys strings

**Comment by Elijas** [comment]
Thanks!
