### ISSUE TITLE
Feature Request: insert selected commands in shell history

### ISSUE THREAD

**Issue by element303** [ricklamers/shell-ai#10]
is it possible to insert selected commands in shell history ?

**Comment by ricklamers** [comment]
We could append to `.bash_history` if it exists, right now we are pretty shell agnostic so not sure whether we want to adopt the burden of doing this for all the various shells. But zsh and bash probably divide the market so could be worth it. Wdyt?

**Comment by JamesHutchison** [comment]
I think it makes sense to support `zsh` and `bash`.

My thinking is the behavior would be to append the ran command as the most recent. Pressing up again would give you the query command itself.

**Comment by ricklamers** [comment]
> We could append to .bash_history if it exists

This won't actually work, in this case it only shows up after shell restart. I think we're going to have to go in the direction of the code @rvangsgaard linked

**Comment by ricklamers** [comment]
Probably won't go with this for `shell-ai`, it will require being inside a terminal emulator like tmux or screen to have buffer access, I'll let other projects go down that route
