### ISSUE TITLE
Facing Exit Status 127

### ISSUE THREAD

**Issue by mdabir1203** [ricklamers/shell-ai#11]
Platform : MacOS 

<img width="688" alt="image" src="https://github.com/ricklamers/shell-ai/assets/66947064/fbfd8cdf-1858-4b33-abcf-3a721f6e7c0d">

**Comment by ricklamers** [comment]
You don’t seem to have terraform installed 👆

**Comment by mdabir1203** [comment]
I saw that a bit later. And found I was running it differently. Speaking of a feedback: 
It would be better if the parsing is given a bit more simpler. It seems unclear

`shai : xxxxxx`
