### ISSUE TITLE
here you find help for Mac user

### ISSUE THREAD

**Issue by MadMacMad** [ricklamers/shell-ai#12]
Create the Directory (if it doesn't exist yet)
To ensure that the directory ~/.config/shell-ai/ exists, you can create it using mkdir with the -p flag, which ensures that parent directories are also created if they don't exist:

mkdir -p ~/.config/shell-ai/
Create the File
To create an empty config.json file, you can use the touch command:

touch ~/.config/shell-ai/config.json
Set Permissions
To set the file permissions to 600, you can use the chmod command:
chmod 600 ~/.config/shell-ai/config.json

**Here's how you can do all of these in one command:**
mkdir -p ~/.config/shell-ai/ && touch ~/.config/shell-ai/config.json && chmod 600 ~/.config/shell-ai/config.json
This one-liner creates the directory, creates the config.json file in that directory, and then sets the file permissions to 600 all in one go.

After you've run these commands, the config.json file should be under ~/.config/shell-ai/, and it should have 600 permissions, meaning that only the owner can read and write to the file.

You can open the config.json file using a text editor of your choice. Here are some ways to do it:

Using Terminal-based Text Editors:
Using Vim

vim ~/.config/shell-ai/config.json
To insert text, press i.
To save and exit, press Esc, then type :wq and press Enter.

Using Nano
nano ~/.config/shell-ai/config.json
To write changes, press Ctrl + O.
To exit, press Ctrl + X.

Using GUI-based Text Editors:
Using Sublime Text (if installed)
subl ~/.config/shell-ai/config.json
Using Visual Studio Code (if installed)
code ~/.config/shell-ai/config.json
Using TextEdit on macOS
open -a "TextEdit" ~/.config/shell-ai/config.json
Any of these commands will open config.json in the text editor you choose, allowing you to view or modify its contents. After you're done, save your changes and close the editor.

**Comment by ricklamers** [comment]
Thanks for contributing this guide :) I’ll close it to keep the Issues focused but people who need it can still find it in the list of all issues/through search engines.
