### ISSUE TITLE
Feature request: Local LLM Support

### ISSUE THREAD

**Issue by illnesse** [ricklamers/shell-ai#19]
How is this even a thing without local LLM support? 🥲 
I love the idea but it's sadly not an option for me if i can't run it 100% locally.

Maybe via [text-generation-webui](https://github.com/oobabooga/text-generation-webui) API for starters

**Comment by ricklamers** [comment]
You can use local LLMs using OPENAI_API_BASE for OpenAI compatible local LLM APIs like https://lmstudio.ai/
