### ISSUE TITLE
Other OpenAI models?

### ISSUE THREAD

**Issue by BjoernHaefner** [ricklamers/shell-ai#22]
If I wanted to use a differen OpenAI model, would [this](https://platform.openai.com/docs/models/models) be the web site to pick from? I wasn't sure where to find this information, as it's not mentiond in the readme :)

**Comment by ricklamers** [comment]
Correct! 👍🏻

You probably want to specifically check via their API which models you have access to: https://platform.openai.com/docs/api-reference/models/list
