### ISSUE TITLE
Duplicated generations

### ISSUE THREAD

**Issue by beimzhan** [ricklamers/shell-ai#24]
![image](https://github.com/ricklamers/shell-ai/assets/109351730/95563b44-9a4a-4c5d-9c21-719d3039d3ab)

I think you should only show unique generations in such cases.

**Comment by ricklamers** [comment]
Nice suggestion!

https://github.com/ricklamers/shell-ai/commit/b78eccabbae6e1188774ff24987db904d39f687d

PS don't do something crazy
