### ISSUE TITLE
Feature request: Add Google Gemini AI model as an option

### ISSUE THREAD

**Issue by rizkidotme** [ricklamers/shell-ai#30]
# Make the Most out of Free Tier Plan: Add Google Gemini AI model as an option

**Feature description**
I would like to have the option to use Google's Gemini AI model instead of OpenAI's model when using shell-ai CLI programs. I think Gemini are arguably on similar league and more cheaper than OpenAI models (pro vs gpt-3.5-turbo), and it would be nice to have the choice of which model to use. This feature request also aims to avoid single point of failure due to reliance on one provider.

**Possible solution and implementation**
According to LangChain's docs, Google's Gemini is supported and integrated with their platform. I suggest adding a flag or an environment variable that allows users to switch between OpenAI and Google Gemini models when using shell-ai. For example, something like:

`shai --model gemini "run terraform dry run thingy"`

or

`export SHELL_AI_MODEL=gemini`

**Alternatives considered**
I have considered using other CLI tools that support Google Gemini, such as ShellGPT or AI-Shell, but I prefer the features and interface of shell-ai.

**Additional context**
Google Gemini is a family of multimodal large language models developed by Google DeepMind, serving as the successor to LaMDA and PaLM 2. It comes in three versions: Gemini Ultra, Gemini Pro, and Gemini Nano, each tailored for different applications and user needs. The Pro version has a generous [free tier](https://ai.google.dev/pricing) plan that may suit the needs of average users.

**Comment by ricklamers** [comment]
Nice idea! Would be great if a contributor could pick this up. I'm currently too busy unfortunately.

**Comment by rizkidotme** [comment]
sorry late response, also a bit busy here. I will try to spend some time and put some effort to it, will let you know update soon!

**Comment by goutham467** [comment]
@ricklamers is this implemented ? I do not see any references to Gemini in code.
