### ISSUE TITLE
Use `gorilla-llm` models?

### ISSUE THREAD

**Issue by ShishirPatil** [ricklamers/shell-ai#7]
Hey Rick, exciting to see more action in this space. Gorilla LLM is a open source project from UC Berkeley, and we have an opensource Gorilla LLM model trained for shell scripts and a CLI interface. If you are interested in this effort - would love to have you contribute to `gorilla-cli`! 

https://github.com/gorilla-llm/gorilla-cli

**Comment by ricklamers** [comment]
Sounds like a great way to combine efforts! Let’s chat

**Comment by ricklamers** [comment]
For `gorilla-llm` use for now people should check out the https://github.com/gorilla-llm/gorilla-cli project.

For simplicity let’s keep Shell AI as a wrapper of LangChain supported models.
